# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
source: src
title: Study blog
email: avsilkin@bhcc.edu
description: >- # this means to ignore newlines until "baseurl:"
  This website is presenting projects and apps created
  while taking a formal training in Computer Science
  and programming. Here I will store projects and
  labs done in programming courses as well as some
  of the materials required according to curriculum.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "asilkin.com" # the base hosstname & protocol for your site, e.g. http://example.com
twitter_username: mrmajestickk
github_username:  Lexlex1991


#Google analytics
google_analytics_id: UA-119838222-1

#port
port: 4444

# Build settings
markdown: kramdown


# Custom
show_excerpts: true
timezone: America/Boston

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#    - Gemfile
#    - Gemfile.lock
   # - CNAME
   # - .gitignore
   # - LICENSE
   # - .sass-cache
   # - node_modules
   # - vendor/bundle/
   # - vendor/cache/
   # - vendor/gems/
   # - vendor/ruby/
gems:
  - jekyll-feed
  - jekyll-seo-tag
